### ISSUE TITLE
Not all heroes wear capes!

### ISSUE THREAD

**Issue by quantatheist** [mcaskill/fever#1]
Hi,
I discovered your repo a few days ago and want to thank you, kiss you and tattoo your name onto my chest (okay, it's getting weird sorry). 
I tried to update Fever to PHP 8, but never got it a working application. A few minutes ago I copied your develop branch and uploaded it onto my server. And yes, it is working best! (Just needed copy old config-Folder)

I hope you maintain Fever 2.0 as long as you can and maybe I gain the skills to support you. 
Thank you very, very, very much! <3

**Comment by mcaskill** [comment]
Hello,

Thank you for the kind words. I'm glad this repository can help other Fever owners to continue benefiting from this sweet software.

Take care,
